{
 "title": "general_up",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "general_up",
   "type": "stat",
   "description": "采集启动状态",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "general_up" }
   ]
  },
  {
   "title": "mysql_链接状态",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(general_mysql_connect_uptime / 60^2 /24)",
     "legendFormat": "运行的天数"
    },
    {
     "expr": "general_mysql_connect_Threads_running",
     "legendFormat": "当前链接线程"
    },
    {
     "expr": "general_mysql_connect_Aborted_connects",
     "legendFormat": "连接中断"
    },
    {
     "expr": "ceil (general_mysql_connect_bytesSent / 1024^2)",
     "legendFormat": "发送（m）"
    },
    {
     "expr": "ceil(abs(general_mysql_connect_bytesReceived / 1024^2))",
     "legendFormat": "收到（m)"
    }
   ]
  },
  {
   "title": "redis up状态",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil (general_redis_connect_uptime_in_seconds / 60^2 /24)",
     "legendFormat": "运行的天数"
    },
    {
     "expr": "ceil(general_redis_connect_used_memory / 1024 /1024)",
     "legendFormat": "used_memory(m)"
    },
    {
     "expr": "ceil(general_redis_connect_used_cpu_user)",
     "legendFormat": "使用的cpu(毫核)"
    }
   ]
  },
  {
   "title": "mysql sql 执行状态统计",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ceil(general_mysql_connect_comCommit)",
     "legendFormat": "commit sql counter"
    },
    {
     "expr": "ceil(general_mysql_connect_comDelete)",
     "legendFormat": "delete sql counter"
    },
    {
     "expr": "ceil(general_mysql_connect_comInsert)",
     "legendFormat": "insert sql counter"
    },
    {
     "expr": "ceil(general_mysql_connect_comRollback)",
     "legendFormat": "rollback sql counter"
    },
    {
     "expr": "ceil (general_mysql_connect_comSelect)",
     "legendFormat": "select sql counter"
    },
    {
     "expr": "ceil (general_mysql_connect_comUpdate)",
     "legendFormat": "update sql counter"
    }
   ]
  },
  {
   "title": "mysql  innodb status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "ceil( general_mysql_connect_innodbBufferPoolReadRequests)",
     "legendFormat": "innodbBufferPoolReadRequests"
    },
    {
     "expr": "ceil( general_mysql_connect_innodbBufferPoolWriteRequests)",
     "legendFormat": "innodbBufferPoolWriteRequests"
    },
    {
     "expr": "ceil(general_mysql_connect_innodbPagesCreated)",
     "legendFormat": "innodbPagesCreated"
    },
    {
     "expr": "ceil(general_mysql_connect_innodbPagesRead)",
     "legendFormat": "innodbPagesRead"
    },
    {
     "expr": "ceil(general_mysql_connect_innodbPagesWritten / 1024^2)",
     "legendFormat": "innodbPagesWritten(m)"
    },
    {
     "expr": "ceil(general_mysql_connect_innodbRowsDeleted)",
     "legendFormat": "innodbRowsDeleted"
    },
    {
     "expr": "ceil(general_mysql_connect_innodbRowsInserted)",
     "legendFormat": "innodbRowsInserted"
    }
   ]
  },
  {
   "title": "redis 连接状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ceil(general_redis_connect_maxclients - general_redis_connect_connected_clients)",
     "legendFormat": "redsi剩余连接数"
    },
    {
     "expr": "ceil( general_redis_connect_io_threads_active)",
     "legendFormat": "活动连接数"
    },
    {
     "expr": "ceil(general_redis_connect_total_net_input_bytes / 1024^2)",
     "legendFormat": "net_input(m)"
    },
    {
     "expr": "ceil(general_redis_connect_total_net_output_bytes / 1000^2)",
     "legendFormat": "net_output(m)"
    }
   ]
  }
 ]
}